export const GET_POKEMONS = 'GET_POKEMONS';
export const GET_POKEMONS_PENDING = 'GET_POKEMONS_PENDING';
export const GET_POKEMONS_FULFILLED = 'GET_POKEMONS_FULFILLED'; 
export const GET_POKEMONS_REJECTED = 'GET_POKEMONS_REJECTED';

export const GET_TYPES = 'GET_TYPES';
export const GET_TYPES_PENDING = 'GET_TYPES_PENDING';
export const GET_TYPES_FULFILLED = 'GET_TYPES_FULFILLED';
export const GET_TYPES_REJECTED = 'GET_TYPES_REJECTED';

export const ADD_POKEMON = 'ADD_POKEMON';
export const ADD_POKEMON_PENDING = 'ADD_POKEMON_PENDING';
export const ADD_POKEMON_FULFILLED = 'ADD_POKEMON_FULFILLED';
export const ADD_POKEMON_REJECTED = 'ADD_POKEMON_REJECTED';

export const LOGIN = 'LOGIN';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';

export const REGISTER = 'REGISTER';
export const REGISTER_PENDING = 'REGISTER_PENDING';
export const REGISTER_FULFILLED = 'REGISTER_FULFILLED';
export const REGISTER_REJECTED = 'REGISTER_REJECTED';