export const GET_POKEMONS = 'GET_POKEMONS';
export const GET_POKEMONS_PENDING = 'GET_POKEMONS_PENDING';
export const GET_POKEMONS_FULFILLED = 'GET_POKEMONS_FULFILLED';
export const GET_POKEMONS_REJECTED = 'GET_POKEMONS_REJECTED';

export const GET_POKEMON = 'GET_POKEMON';
export const GET_POKEMON_PENDING = 'GET_POKEMON_PENDING';
export const GET_POKEMON_FULFILLED = 'GET_POKEMON_FULFILLED';
export const GET_POKEMON_REJECTED = 'GET_POKEMON_REJECTED';

export const GET_MORE_POKEMONS = 'GET_MORE_POKEMONS';
export const GET_MORE_POKEMONS_PENDING = 'GET_MORE_POKEMONS_PENDING';
export const GET_MORE_POKEMONS_FULFILLED = 'GET_MORE_POKEMONS_FULFILLED';
export const GET_MORE_POKEMONS_REJECTED = 'GET_MORE_POKEMONS_REJECTED';

export const GET_TYPES = 'GET_TYPES';
export const GET_TYPES_PENDING = 'GET_TYPES_PENDING';
export const GET_TYPES_FULFILLED = 'GET_TYPES_FULFILLED';
export const GET_TYPES_REJECTED = 'GET_TYPES_REJECTED';

export const ADD_POKEMON = 'ADD_POKEMON';
export const ADD_POKEMON_PENDING = 'ADD_POKEMON_PENDING';
export const ADD_POKEMON_FULFILLED = 'ADD_POKEMON_FULFILLED';
export const ADD_POKEMON_REJECTED = 'ADD_POKEMON_REJECTED';

export const UPDATE_POKEMON = 'UPDATE_POKEMON';
export const UPDATE_POKEMON_PENDING = 'UPDATE_POKEMON_PENDING';
export const UPDATE_POKEMON_FULFILLED = 'UPDATE_POKEMON_FULFILLED';
export const UPDATE_POKEMON_REJECTED = 'UPDATE_POKEMON_REJECTED';

export const DELETE_POKEMON = 'DELETE_POKEMON';
export const DELETE_POKEMON_PENDING = 'DELETE_POKEMON_PENDING';
export const DELETE_POKEMON_FULFILLED = 'DELETE_POKEMON_FULFILLED';
export const DELETE_POKEMON_REJECTED = 'DELETE_POKEMON_REJECTED';

export const LOGIN = 'LOGIN';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';

export const REGISTER = 'REGISTER';
export const REGISTER_PENDING = 'REGISTER_PENDING';
export const REGISTER_FULFILLED = 'REGISTER_FULFILLED';
export const REGISTER_REJECTED = 'REGISTER_REJECTED';
